/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import DAO.AdminDAO;
import DAO.ThongKeDAO;
import Model.Admin;
import java.util.ArrayList;

/**
 *
 * @author pvsla
 */
public class QuanLyUI extends javax.swing.JFrame {

    ThongKeDAO tkdao = new ThongKeDAO();
    ArrayList<Admin> listad;
    DangNhapJDialog lg = new DangNhapJDialog();
    String us = lg.getUser();

    /**
     * Creates new form QuanLyUI
     */
    public QuanLyUI() {
        initComponents();
        setLocationRelativeTo(null);
        loadad();
        TongSV();
        TongSach();
        TongTheLoaiTLS();
        TongPM();
    }

    public void TongTheLoaiTLS() {
        int tongso = tkdao.TKsoTheLoaiTLS();
        lblSoTLS.setText(String.valueOf(tongso));
    }

    public void TongSV() {
        int tongso = tkdao.TKsoSV();
        lblSoSV.setText(String.valueOf(tongso));
    }

    public void TongSach() {
        int tongso = tkdao.TKsoSach();
        lblSoSach.setText(String.valueOf(tongso));
    }

    public void TongPM() {
        int tongso = tkdao.TKTongPM();
        lblSoPM.setText(String.valueOf(tongso));
    }

    public void loadad() {
        AdminDAO addao = new AdminDAO();
        listad = addao.LoadMa(us);

        for (Admin ad : listad) {
            Object[] row = new Object[]{
                ad.getUsername(), ad.getPassword(), ad.getTen()
            };
            lblName.setText(ad.getTen());
        }
    }

    public void ThongKe(int index) {
        ThongKe tk = new ThongKe(index);
        tk.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlQLSV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSoSV = new javax.swing.JLabel();
        pnlTLS = new javax.swing.JPanel();
        lblSoTLS = new javax.swing.JLabel();
        pnlQLS = new javax.swing.JPanel();
        lblSoSach = new javax.swing.JLabel();
        pnlPM = new javax.swing.JPanel();
        lblSoPM = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        mnb = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mniThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLTL = new javax.swing.JMenuItem();
        mniQLS = new javax.swing.JMenuItem();
        mniQLSV = new javax.swing.JMenuItem();
        mniQLPM = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKSV = new javax.swing.JMenuItem();
        mniTKS = new javax.swing.JMenuItem();
        mniTKTL = new javax.swing.JMenuItem();
        mniTKPM = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniTroGiup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlWelcome.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome"));

        jLabel1.setText("Xin Chào:");

        lblName.setText("Tên...");

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlQLSV.setBorder(javax.swing.BorderFactory.createTitledBorder("Sinh Viên\n\n"));
        pnlQLSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQLSVMouseClicked(evt);
            }
        });

        jLabel2.setText("Quản lý Sinh Viên");

        lblSoSV.setText("slsv");

        javax.swing.GroupLayout pnlQLSVLayout = new javax.swing.GroupLayout(pnlQLSV);
        pnlQLSV.setLayout(pnlQLSVLayout);
        pnlQLSVLayout.setHorizontalGroup(
            pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSVLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(pnlQLSVLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlQLSVLayout.setVerticalGroup(
            pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSVLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(lblSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pnlTLS.setBorder(javax.swing.BorderFactory.createTitledBorder("Thể Loại Sách"));
        pnlTLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTLSMouseClicked(evt);
            }
        });

        lblSoTLS.setText("jLabel3");

        javax.swing.GroupLayout pnlTLSLayout = new javax.swing.GroupLayout(pnlTLS);
        pnlTLS.setLayout(pnlTLSLayout);
        pnlTLSLayout.setHorizontalGroup(
            pnlTLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTLSLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSoTLS)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlTLSLayout.setVerticalGroup(
            pnlTLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTLSLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblSoTLS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlQLS.setBorder(javax.swing.BorderFactory.createTitledBorder("Sách"));
        pnlQLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQLSMouseClicked(evt);
            }
        });

        lblSoSach.setText("jLabel3");

        javax.swing.GroupLayout pnlQLSLayout = new javax.swing.GroupLayout(pnlQLS);
        pnlQLS.setLayout(pnlQLSLayout);
        pnlQLSLayout.setHorizontalGroup(
            pnlQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblSoSach)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlQLSLayout.setVerticalGroup(
            pnlQLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblSoSach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPM.setBorder(javax.swing.BorderFactory.createTitledBorder("Phiếu Mượn"));
        pnlPM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPMMouseClicked(evt);
            }
        });

        lblSoPM.setText("jLabel3");

        javax.swing.GroupLayout pnlPMLayout = new javax.swing.GroupLayout(pnlPM);
        pnlPM.setLayout(pnlPMLayout);
        pnlPMLayout.setHorizontalGroup(
            pnlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPMLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSoPM)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlPMLayout.setVerticalGroup(
            pnlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPMLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblSoPM)
                .addGap(39, 39, 39))
        );

        pnlThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống Kê"));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlQLSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlQLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlQLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlQLSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuHeThong.setText("Hệ Thống");

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Lock.png"))); // NOI18N
        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Log out.png"))); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        mnb.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mniQLTL.setText("Quản lý thể loại");
        mniQLTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLTLActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLTL);

        mniQLS.setText("Quản lý sách");
        mniQLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLS);

        mniQLSV.setText("Quản lý sinh viên");
        mniQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSVActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLSV);

        mniQLPM.setText("Quản lý phiếu mượn");
        mniQLPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLPMActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLPM);

        mnb.add(mnuQuanLy);

        mnuThongKe.setText("Thống Kê");

        mniTKSV.setText("Thống Kê Sinh Viên");
        mniTKSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKSVActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKSV);

        mniTKS.setText("Thống Kê Sách");
        mniTKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKSActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKS);

        mniTKTL.setText("Thống Kê Thể Loại");
        mniTKTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKTLActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKTL);

        mniTKPM.setText("Thống Kê Phiếu Mượn");
        mniTKPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKPMActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKPM);

        mnb.add(mnuThongKe);

        mnuTroGiup.setText("Trợ Giúp");

        mniTroGiup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mniTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Help.png"))); // NOI18N
        mniTroGiup.setText("Giới thiệu");
        mnuTroGiup.add(mniTroGiup);

        mnb.add(mnuTroGiup);

        setJMenuBar(mnb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniTKTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKTLActionPerformed
        // TODO add your handling code here:
        ThongKe(2);
        dispose();
    }//GEN-LAST:event_mniTKTLActionPerformed

    private void pnlQLSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSVMouseClicked
        // TODO add your handling code here:
        QuanLySinhVien qlsv = new QuanLySinhVien();
        qlsv.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlQLSVMouseClicked

    private void pnlTLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTLSMouseClicked
        // TODO add your handling code here:
        QuanLyTheLoaiSach qltls = new QuanLyTheLoaiSach();
        qltls.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlTLSMouseClicked

    private void pnlQLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSMouseClicked
        // TODO add your handling code here:
        QuanLySach qls = new QuanLySach();
        qls.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlQLSMouseClicked

    private void pnlPMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPMMouseClicked
        // TODO add your handling code here:
        QuanLyPhieuMuon qlpm = new QuanLyPhieuMuon();
        qlpm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlPMMouseClicked

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        // TODO add your handling code here:
        ThongKe tk = new ThongKe();
        tk.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhauUI dmk = new DoiMatKhauUI();
        dmk.setVisible(true);
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhapJDialog lg = new DangNhapJDialog();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniQLTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLTLActionPerformed
        // TODO add your handling code here:
        QuanLyTheLoaiSach qltls = new QuanLyTheLoaiSach();
        qltls.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniQLTLActionPerformed

    private void mniQLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSActionPerformed
        // TODO add your handling code here:
        QuanLySach qls = new QuanLySach();
        qls.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniQLSActionPerformed

    private void mniQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSVActionPerformed
        // TODO add your handling code here:
        QuanLySinhVien qlsv = new QuanLySinhVien();
        qlsv.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniQLSVActionPerformed

    private void mniQLPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLPMActionPerformed
        // TODO add your handling code here:
        QuanLyPhieuMuon qlpm = new QuanLyPhieuMuon();
        qlpm.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniQLPMActionPerformed

    private void mniTKSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKSVActionPerformed
        // TODO add your handling code here:
        ThongKe(0);
        dispose();
    }//GEN-LAST:event_mniTKSVActionPerformed

    private void mniTKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKSActionPerformed
        // TODO add your handling code here:
        ThongKe(1);
        dispose();
    }//GEN-LAST:event_mniTKSActionPerformed

    private void mniTKPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKPMActionPerformed
        // TODO add your handling code here:
        ThongKe(3);
        dispose();
    }//GEN-LAST:event_mniTKPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSoPM;
    private javax.swing.JLabel lblSoSV;
    private javax.swing.JLabel lblSoSach;
    private javax.swing.JLabel lblSoTLS;
    private javax.swing.JMenuBar mnb;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniQLPM;
    private javax.swing.JMenuItem mniQLS;
    private javax.swing.JMenuItem mniQLSV;
    private javax.swing.JMenuItem mniQLTL;
    private javax.swing.JMenuItem mniTKPM;
    private javax.swing.JMenuItem mniTKS;
    private javax.swing.JMenuItem mniTKSV;
    private javax.swing.JMenuItem mniTKTL;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenuItem mniTroGiup;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlPM;
    private javax.swing.JPanel pnlQLS;
    private javax.swing.JPanel pnlQLSV;
    private javax.swing.JPanel pnlTLS;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlWelcome;
    // End of variables declaration//GEN-END:variables
}
